version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5433:5432" #change it to your port
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow:
    build: ./airflow
    container_name: airflow
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW_CONN_AIRFLOW_POSTGRES: "postgres://airflow:airflow@postgres:5432/airflow"
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - airflow_logs:/opt/airflow/logs
      - airflow_plugins:/opt/airflow/plugins
      - ./python-ingestion:/opt/airflow/python-ingestion
      - ./data:/opt/airflow/data
      - ./r-transformation:/opt/airflow/r-transformation
      - ./sql:/opt/airflow/sql
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create --username admin --password admin --firstname admin --lastname admin --role Admin --email admin@example.com &&
      airflow webserver & airflow scheduler
      "

volumes:
  postgres_data:
  airflow_logs:
  airflow_plugins:
