volumes:
  postgres-data:
    driver: local
  kestra-data:
    driver: local

services:

  # -------------------------
  # PostgreSQL Database
  # -------------------------
  postgres:
    image: postgres:15
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: kestra
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: k3str4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - "5433:5432"

  # -------------------------
  # Kestra Orchestration
  # -------------------------
  kestra:
    image: kestra/kestra:latest
    container_name: kestra
    pull_policy: always
    user: "root"
    command: sh -c "until pg_isready -h postgres -p 5432 -U kestra; do sleep 2; done; kestra server standalone"
    volumes:
      - kestra-data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kestra-wd:/tmp/kestra-wd
    environment:
      KESTRA_CONFIGURATION: |
        server:
          basicAuth:
            username: admin@kestra.io
            password: Admin1234
        repository:
          type: POSTGRES
          postgres:
            url: jdbc:postgresql://postgres:5432/kestra
            username: kestra
            password: k3str4
        queue:
          type: POSTGRES
          postgres:
            url: jdbc:postgresql://postgres:5432/kestra
            username: kestra
            password: k3str4
        storage:
          type: LOCAL
          local:
            basePath: "/app/storage"
        tasks:
          tmpDir:
            path: /tmp/kestra-wd/tmp
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy

  # -------------------------
  # Python Service
  # -------------------------
  python:
    image: python:3.10
    container_name: python-dev
    command: tail -f /dev/null
    volumes:
      - ./python:/workspace
    working_dir: /workspace
    environment:
      PYTHONUNBUFFERED: 1
    depends_on:
      postgres:
        condition: service_healthy

  # -------------------------
  # R Service
  # -------------------------
  r:
    image: r-base:latest
    platform: linux/arm64
    container_name: r-dev
    command: tail -f /dev/null
    volumes:
      - ./r:/workspace
    working_dir: /workspace
    depends_on:
      postgres:
        condition: service_healthy
